// @ts-nocheck
import * as __fd_glob_52 from "../content/docs/usage/translations.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/usage/share-embed.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/usage/mindmap.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/usage/index.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/usage/chat.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/usage/browse-docs.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/usage/add-repository.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/api-reference/repositories.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/api-reference/incremental-updates.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/api-reference/chat.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/api-reference/auth.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/api-reference/admin.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/faq/index.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/mcp/index.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/getting-started/quick-start-docker.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/getting-started/local-development.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/getting-started/interface-tour.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/getting-started/index.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/getting-started/first-repository.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/deployment/windows.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/deployment/upgrade-backup.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/deployment/reverse-proxy.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/deployment/postgresql.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/deployment/index.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/deployment/environment-variables.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/deployment/docker-compose.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/deployment/ai-providers.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/advanced/prompts.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/advanced/pipeline.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/advanced/index.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/advanced/incremental-updates.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/advanced/data-models.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/advanced/contributing.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/advanced/architecture.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/admin-guide/users-roles.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/admin-guide/system-settings.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/admin-guide/skills-mcps.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/admin-guide/repositories.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/admin-guide/index.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/admin-guide/github-import.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/admin-guide/chat-assistant.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/admin-guide/api-keys.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/admin-guide/ai-providers.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/index.mdx?collection=docs"
import { default as __fd_glob_8 } from "../content/docs/usage/meta.json?collection=docs"
import { default as __fd_glob_7 } from "../content/docs/faq/meta.json?collection=docs"
import { default as __fd_glob_6 } from "../content/docs/mcp/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../content/docs/getting-started/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/deployment/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/advanced/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/api-reference/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/admin-guide/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "admin-guide/meta.json": __fd_glob_1, "api-reference/meta.json": __fd_glob_2, "advanced/meta.json": __fd_glob_3, "deployment/meta.json": __fd_glob_4, "getting-started/meta.json": __fd_glob_5, "mcp/meta.json": __fd_glob_6, "faq/meta.json": __fd_glob_7, "usage/meta.json": __fd_glob_8, }, {"index.mdx": __fd_glob_9, "admin-guide/ai-providers.mdx": __fd_glob_10, "admin-guide/api-keys.mdx": __fd_glob_11, "admin-guide/chat-assistant.mdx": __fd_glob_12, "admin-guide/github-import.mdx": __fd_glob_13, "admin-guide/index.mdx": __fd_glob_14, "admin-guide/repositories.mdx": __fd_glob_15, "admin-guide/skills-mcps.mdx": __fd_glob_16, "admin-guide/system-settings.mdx": __fd_glob_17, "admin-guide/users-roles.mdx": __fd_glob_18, "advanced/architecture.mdx": __fd_glob_19, "advanced/contributing.mdx": __fd_glob_20, "advanced/data-models.mdx": __fd_glob_21, "advanced/incremental-updates.mdx": __fd_glob_22, "advanced/index.mdx": __fd_glob_23, "advanced/pipeline.mdx": __fd_glob_24, "advanced/prompts.mdx": __fd_glob_25, "deployment/ai-providers.mdx": __fd_glob_26, "deployment/docker-compose.mdx": __fd_glob_27, "deployment/environment-variables.mdx": __fd_glob_28, "deployment/index.mdx": __fd_glob_29, "deployment/postgresql.mdx": __fd_glob_30, "deployment/reverse-proxy.mdx": __fd_glob_31, "deployment/upgrade-backup.mdx": __fd_glob_32, "deployment/windows.mdx": __fd_glob_33, "getting-started/first-repository.mdx": __fd_glob_34, "getting-started/index.mdx": __fd_glob_35, "getting-started/interface-tour.mdx": __fd_glob_36, "getting-started/local-development.mdx": __fd_glob_37, "getting-started/quick-start-docker.mdx": __fd_glob_38, "mcp/index.mdx": __fd_glob_39, "faq/index.mdx": __fd_glob_40, "api-reference/admin.mdx": __fd_glob_41, "api-reference/auth.mdx": __fd_glob_42, "api-reference/chat.mdx": __fd_glob_43, "api-reference/incremental-updates.mdx": __fd_glob_44, "api-reference/repositories.mdx": __fd_glob_45, "usage/add-repository.mdx": __fd_glob_46, "usage/browse-docs.mdx": __fd_glob_47, "usage/chat.mdx": __fd_glob_48, "usage/index.mdx": __fd_glob_49, "usage/mindmap.mdx": __fd_glob_50, "usage/share-embed.mdx": __fd_glob_51, "usage/translations.mdx": __fd_glob_52, });